# Generated by Django 5.2.8 on 2025-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("total_equipment", models.IntegerField()),
                ("average_flowrate", models.FloatField()),
                ("average_pressure", models.FloatField()),
                ("average_temperature", models.FloatField()),
            ],
        ),
    ]
